### ISSUE TITLE
sorting package not found

### ISSUE THREAD

**Issue by nzinfo** [ContinuumIO/numbapro-spca#1]
I'm a numbapro's user, and tring to find some examples of how to use numbapro on GPU. I was excited when I found the project. But, after some search attempt, I find there is no such a package named 
numbapro.cudalib.sorting. This is a internal version of numbapro? If so, when will the version been released ? 

ps: the code say, 
from numbapro.cudalib.sorting.segsort import segmented_sort

**Comment by sklam** [comment]
This repository is currently using an internal version of numbapro.  It is meant to be a collaboration space with our partner.  The sorting algorithm needs a bit more polishing before it can be released.  I don't have an exact date.

**Comment by nzinfo** [comment]
Thank you for the information :)
